import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { createClient } from "@supabase/supabase-js";
import nodemailer from "nodemailer";
import PDFDocument from "pdfkit";
import QRCode from "qrcode";

dotenv.config({ path: "server/.env" });

const url = process.env.SUPABASE_URL.trim();
const key = process.env.SUPABASE_SERVICE_ROLE_KEY.trim();

const supabaseAdmin = createClient(url, key);

const app = express();
app.use(cors());
app.use(express.json());

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: Number(process.env.SMTP_PORT || 587),
  secure: false,
  auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
});

transporter.verify(err => {
  if (err) console.error("SMTP ERROR:", err);
  else console.log("✅ SMTP READY");
});

/* ================= EMAIL TEMPLATE ENGINE ================= */

function emailLayout(title, body) {
  return `
<div style="background:#f1f5f9;padding:40px;font-family:Segoe UI,Arial">
  <div style="max-width:680px;margin:auto;background:white;border-radius:16px;
              box-shadow:0 25px 60px rgba(0,0,0,.12);overflow:hidden">

    <div style="background:linear-gradient(135deg,#1d4ed8,#3b82f6);
                padding:26px;color:white">
      <h2 style="margin:0">${title}</h2>
      <p style="margin:4px 0 0;font-size:13px;opacity:.9">
        Thannmanngaadi Foundation • Official Communication
      </p>
    </div>

    <div style="padding:36px;color:#334155;font-size:15px;line-height:1.7">
      ${body}
    </div>

    <div style="background:#f8fafc;padding:18px;text-align:center;
                font-size:12px;color:#64748b">
      © Thannmanngaadi Foundation • Automated secure email  
      This message was generated by our official NGO system.
    </div>
  </div>
</div>`;
}

/* ================= PDF CERTIFICATE ================= */

async function generatePDF(name, amount, id, verifyUrl) {
  return new Promise(async (resolve) => {
    const doc = new PDFDocument();
    const chunks = [];
    doc.on("data", c => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    doc.fontSize(26).text("Donation Certificate", { align: "center" });
    doc.moveDown();
    doc.fontSize(18).text(name, { align: "center" });
    doc.moveDown();
    doc.text(`Donation: ₹${amount}`, { align: "center" });

    const qr = await QRCode.toDataURL(verifyUrl);
    const qrBuf = Buffer.from(qr.split(",")[1], "base64");
    doc.image(qrBuf, 250, 350, { width: 100 });

    doc.end();
  });
}

/* ================= DONATION EMAIL ================= */

app.post("/donation/send-certificate", async (req, res) => {
  const { name, email, amount } = req.body;
  const id = "CERT-" + Date.now();
  const verifyUrl = `https://yourdomain.com/verify/${id}`;

  const pdf = await generatePDF(name, amount, id, verifyUrl);

  const body = `
<p>Dear <b>${name}</b>,</p>
<p>We gratefully acknowledge your generous donation of 
<b style="color:#1d4ed8">₹${amount}</b>.</p>

<p>Your support strengthens our mission to empower communities.</p>

<p><b>Certificate ID:</b> ${id}</p>
<p><a href="${verifyUrl}" style="color:#2563eb">Verify Certificate</a></p>

<p>With sincere appreciation,<br/>
<b>Thannmanngaadi Foundation</b></p>`;

  await transporter.sendMail({
    from: `"Thannmanngaadi Foundation" <${process.env.SMTP_USER}>`,
    to: email,
    subject: "Official Donation Acknowledgement",
    html: emailLayout("Donation Confirmation", body),
    attachments: [{ filename: `${id}.pdf`, content: pdf }],
  });

  res.json({ ok: true });
});

/* ================= VOLUNTEER APPLY ================= */

app.post("/api/volunteer/apply", async (req, res) => {
  try {
    const { name, email } = req.body;

    if (!name || !email) {
      return res.status(400).json({ ok: false, error: "Missing fields" });
    }

    /* ================= ADMIN NOTIFICATION ================= */

    const adminBody = `
<p><b>New Volunteer Application Received</b></p>

<p>
<b>Name:</b> ${name}<br/>
<b>Email:</b> ${email}
</p>

<p>
Please review this application in the admin dashboard and take necessary action.
</p>
`;

    await transporter.sendMail({
      from: `"Volunteer System" <${process.env.SMTP_USER}>`,
      to: process.env.ADMIN_EMAIL,   // ✅ ADMIN MAIL
      subject: "🚨 New Volunteer Application",
      html: emailLayout("New Volunteer Application", adminBody),
    });

    /* ================= VOLUNTEER CONFIRMATION ================= */

    const volunteerBody = `
<p>Dear <b>${name}</b>,</p>

<p>
Thank you for applying to become a volunteer with
<b>Thannmanngaadi Foundation</b>.
</p>

<p>
Our coordination team has received your application and will
review it shortly.
</p>

<p>
You will be informed via email once a decision is made.
</p>

<p>
Warm regards,<br/>
<b>Volunteer Coordination Team</b><br/>
Thannmanngaadi Foundation
</p>
`;

    await transporter.sendMail({
      from: `"Thannmanngaadi Foundation" <${process.env.SMTP_USER}>`,
      to: email,
      subject: "Volunteer Application Received ✔",
      html: emailLayout("Application Received", volunteerBody),
    });

    console.log("✅ Volunteer + Admin emails sent");

    res.json({ ok: true });

  } catch (err) {
    console.error("❌ Volunteer apply error:", err);
    res.status(500).json({ ok: false });
  }
});

/* ================= VOLUNTEER STATUS ================= */

app.post("/admin/volunteer-status", async (req, res) => {
  const { name, email, status } = req.body;

  const body =
    status === "Approved"
      ? `<p>Congratulations ${name} 🎉</p>
         <p>Your volunteer application has been approved.</p>
         <p>Welcome to the Thannmanngaadi family.</p>`
      : `<p>Dear ${name},</p>
         <p>We appreciate your interest. Unfortunately we cannot proceed at this time.</p>
         <p>Please stay connected for future opportunities.</p>`;

  await transporter.sendMail({
    from: `"NGO Administration" <${process.env.SMTP_USER}>`,
    to: email,
    subject: "Volunteer Application Update",
    html: emailLayout("Application Status", body),
  });

  res.json({ ok: true });
});

/* ================= ADMIN SUPPORT REPLY ================= */

app.post("/admin/reply-message", async (req, res) => {
  const { to, message } = req.body;

  const body = `<p>${message}</p><p>Warm regards,<br/>Support Team</p>`;

  await transporter.sendMail({
    from: `"NGO Support" <${process.env.SMTP_USER}>`,
    to,
    subject: "Official Support Reply",
    html: emailLayout("Support Response", body),
  });

  res.json({ ok: true });
});

/* ================= SERVER ================= */

app.listen(5050, () => console.log("🚀 Server running on 5050"));